### ISSUE TITLE
message size problem

### ISSUE THREAD

**Issue by Gromina** [aberant/tuio-ruby#2]
I've found the problem with message arguments parsing.
Maybe it is because of TUIO protocol changes, dunno

It definetely happens when I check 'send width & height' in CCV.
As I understand in this case CCV sends more data in messages.

I hacked the code to see arguments, there are actually 2 more arguments.

Maybe limiting arguments array size is the solution (tuio_client.rb:42)
## here is a dump:

./tuio-ruby/lib/tuio-ruby/tuio_client.rb:91:in `initialize': wrong number of arguments (8 for 6) (ArgumentError)
        from ./tuio-ruby/lib/tuio-ruby/tuio_client.rb:91:in`new'
        from ./tuio-ruby/lib/tuio-ruby/tuio_client.rb:91:in `track_tuio_cursor'
        from ./tuio-ruby/lib/tuio-ruby/tuio_client.rb:42:in`initialize'
        from XXXXXXX/ruby/lib/ruby/gems/1.8/gems/osc-ruby-0.2.0/lib/osc-ruby/server.rb:50:in `call'
        from XXXXXXX/ruby/lib/ruby/gems/1.8/gems/osc-ruby-0.2.0/lib/osc-ruby/server.rb:50:in`sendmesg'
        from XXXXXXX/ruby/lib/ruby/gems/1.8/gems/osc-ruby-0.2.0/lib/osc-ruby/server.rb:48:in `each'
        from XXXXXXX/ruby/lib/ruby/gems/1.8/gems/osc-ruby-0.2.0/lib/osc-ruby/server.rb:48:in`sendmesg'
        from XXXXXXX/ruby/lib/ruby/gems/1.8/gems/osc-ruby-0.2.0/lib/osc-ruby/server.rb:80:in `dispatch_message'
         ... 8 levels...
        from ./tuio-ruby/lib/tuio-ruby/tuio_client.rb:52:in`initialize'
        from ./tuio-ruby/lib/tuio-ruby/tuio_client.rb:52:in `new'
        from ./tuio-ruby/lib/tuio-ruby/tuio_client.rb:52:in`start'
        from ctrl_server.rb:34

**Comment by aberant** [comment]
i've setup the code to only use the first 6 parameters for cursors until i can provide official blob support. pull the latest code from github, or install the 0.2.4 gem and let me know if it fixes your project.  i'm able to run CCV locally without it exploding.

**Comment by Gromina** [comment]
It works now without a problem.

Thanks again.
